### ISSUE TITLE
Unable to acquire token for tenant 'organizations' with error 'Operation returned invalid status code 'BadRequest'

### ISSUE THREAD

**Issue by hacknorris** [mandiant/Azure_Workshop#4] opened 2022-08-01 17:28 UTC
Hello!  Am working through KC1. Have logged into a Linux VM, and connected to azure with the Peter Williams account. I'm able to extract an access token.  When I use this token on my Windows VM, I'm getting "Unable to acquire token for tenant 'organizations' with error 'Operation returned invalid status code 'BadRequest'".  Connect-AzAccount : Operation returned invalid status code 'BadRequest'.  

Using the below connection string with AccessToken.  

Would great appreciate any help or insight to this error.

Additionally -- I thought it might have been related to my other MFA enforcement policy, and so have turned that off temporarily.  Do these scenarios (as a base assumption need MFA off or disabled?).

The Linux user CA policy is working as intended :)

****
- from PW user department field, he's expected to log in from a Linux machine (Conditional Access rules)
- extract access token from Linux machine or using az on Windows (az seems to bypass the application type)
az account get-access-token

- import the above access token and login on a Windows machine
Connect-AzAccount -AccountId <\UserName> -AccessToken $token
****

**Comment by RoxanaKovaci** [comment] 2022-08-01 18:38
Hello there,

To get a more verbose error output, I'd suggest adding `-Verbose` and / or `-Debug` flags to your `Connect-AzAccount` command. This will help with the troubleshooting in general.

Could you please double-check your az context with the below?

`Get-AzContext`

I suspect you might be logged in multiple tenants simultaneously. If so, just clear your context and re-login.

`Clear-AzContext`
`Connect-AzAccount -Tenant <tenant-id> -AccountId <UserName> -AccessToken $token`

**Comment by hacknorris** [comment] 2022-08-01 19:40
Thankyou so much for the quick response!!  I've double checked context and cleared az-context.  The debug switch is giving some additional information.  Does it matter if I'm logged into the Windows VM with a local admin account, or should it be tied to the Peter Williams account?   Please see the additional debugging info.

**Comment by RoxanaKovaci** [comment] 2022-08-02 09:41
hey - I'm unable to reproduce this issue, with or without MFA enabled. Found a similar thread which might help - https://github.com/Azure/azure-powershell/issues/13530 where it seems to be the general opinion of being logged in multiple accounts / tenants simultaneously. I'd also suggest to clear browser cache if logging in via the browser as well as remove the json files AzureRmContext.json and AzureRmContextSettings.json (as these contain Azure cached credentials) from `c:\users\$env:USERNAME\.azure\` on the Windows machine where you're logging in from.

**Comment by RoxanaKovaci** [comment] 2022-08-04 13:45
closing this as the issue relates to the Azure subscription / tenant rather than the labs deployment.

**Closed by RoxanaKovaci** 2022-08-04 13:45 UTC
